server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
project:
  nema: hana-package

spring:
  application:
    name: Hana-package-Server
  profiles:
    active: local
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
  servlet:
    multipart:
      max-file-size: '100MB'
      max-request-size: '100MB'
jwt:
  secret: hn-package
  validity: 50000

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: hana-package.syopingbaeg.com
    region:
      static: ap-northeast-2
    stack:
      auto: false

ncloud:
  access-key: ${NAVER_ACCESS_KEY}
  secret-key: ${NAVER_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    profile: ${spring.profiles.active}
  environment:
    os: ${os.name}
    timezone: ${user.timezone}