spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:./h2db/hn_package;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
      username: sa
  flyway:
    locations: classpath:db/data/common, classpath:db/data/test
  jpa:
    show-sql: true

ncloud:
  email:
    address: 'dhflhn@gmail.com'
    url: https://mail.apigw.ntruss.com
    path: /api/v1/mails
